# Nombre de la aplicacion
spring:
  application:
    name: restaurant-api

# Configuracion de PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_db
    username: postgres
    password: Datos2026
    driver-class-name: org.postgresql.Driver

# Configuracion de Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

# Puerto del servidor
server:
  port: 8080
